name: "Automated update"
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
      with:
        ref: master
    - name: Install nix
      uses: cachix/install-nix-action@master
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/latest/download/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Setup cachix
      uses: cachix/cachix-action@master
      with:
        name: linyinfeng
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Cache
      uses: actions/cache@main
      with:
        path: |
          pkgs/_sources/.shake.database
        key: ${{ runner.os }}-${{ hashFiles('pkgs/updater/src/*') }}-${{ hashFiles('pkgs/_sources/generated.nix') }}
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles('pkgs/updater/src/*') }}-
    - name: Run updater
      run: |
        # update and set variables
        # - COMMIT_TITLE
        # - COMMIT_BODY
        # - UPDATER_CHANGELOG
        nix develop --command update
    - name: Nix flake update
      run: |
        # do nix flake update if sources were updated
        if [ -n "$(git status --porcelain)" ]; then
          nix flake update
        fi
    - name: Create pull request
      if: ${{ format('{0}{1}', env.COMMIT_TITLE, env.COMMIT_BODY) != '' }}
      uses: peter-evans/create-pull-request@main
      id: cpr
      with:
        token: '${{ secrets.PAT_FOR_CREATE_PULL_REQUEST }}'
        commit-message: |
          ${{ env.COMMIT_TITLE }}${{ env.COMMIT_BODY }}
        title: Automated update
        author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        body: |
          ###### Changelog

          ```text
          ${{ env.UPDATER_CHANGELOG }}
          ```
        branch: 'create-pull-request/update'
        assignees: |
          linyinfeng
        reviewers: |
          linyinfeng
        labels: |
          auto merge
        delete-branch: true
