name: "Automated update"
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
      with:
        ref: master
    - name: Install nix
      uses: cachix/install-nix-action@master
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/latest/download/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Setup cachix
      uses: cachix/cachix-action@master
      with:
        name: linyinfeng
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Cache
      uses: actions/cache@main
      with:
        path: |
          pkgs/_build
          !pkgs/_build/generated.nix
        key: ${{ runner.os }}-${{ hashFiles('pkgs/updater/src/*') }}-${{ hashFiles('pkgs/_build/generated.nix') }}
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles('pkgs/updater/src/*') }}-
    - name: Run updater
      run: |
        cp ./pkgs/sources.nix /tmp/old-sources.nix
        nix develop --command update
        nix eval --expr '
          (builtins.getFlake "'$PWD'").lib.versionDiff {
            oldSources = /tmp/old-sources.nix;
            newSources = ./pkgs/sources.nix;
          }' --impure --raw > /tmp/changelog

        echo "UPDATER_CHANGELOG<<EOF" >> $GITHUB_ENV
        cat /tmp/changelog >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        changelog_lines=$(wc --lines /tmp/changelog | cut -d ' ' -f 1)
        if [ "$changelog_lines" -eq "1" ]; then
            echo "COMMIT_TITLE=$(cat /tmp/changelog)" >> $GITHUB_ENV
            echo "COMMIT_BODY=" >> $GITHUB_ENV
        else
            echo "COMMIT_TITLE=Update multiple packages" >> $GITHUB_ENV
            echo "COMMIT_BODY<<EOF" >> $GITHUB_ENV
            echo -ne "\n\n" >> $GITHUB_ENV
            cat /tmp/changelog >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
        fi
    - name: Nix flake update
      run: |
        # do nix flake update if sources were updated
        if [ -n "$(git status --porcelain)" ]; then
          nix flake update
        fi
    - name: Craete pull request
      uses: peter-evans/create-pull-request@main
      with:
        token: '${{ secrets.PAT_FOR_CREATE_PULL_REQUEST }}'
        commit-message: |
          ${{ env.COMMIT_TITLE }}${{ env.COMMIT_BODY }}
        committer: GitHub <noreply@github.com>
        author: GitHub <noreply@github.com>
        title: Automated update
        body: |
          ###### Changelog

          ```text
          ${{ env.UPDATER_CHANGELOG }}
          ```
        branch: 'create-pull-request/update'
        delete-branch: true
        reviewers: linyinfeng
        assignees: linyinfeng
